[1] "BELEM"                      "PARAUAPEBAS"                "MARABA"                     "CANAA DOS CARAJAS"          "ANANINDEUA"                
[6] "CASTANHAL"                  "JACUNDA"                    "ORIXIMINA"                  "VIGIA"                      "BREU BRANCO"               
[11] "TUCURUI"                    "TUCUMA"                     "PARAGOMINAS"                "DOM ELISEU"                 "SAO FELIX DO XINGU"        
[16] "JACAREACANGA"               "REDENCAO"                   "SALINOPOLIS"                "RONDON DO PARA"             "ALTAMIRA"                  
[21] "BARCARENA"                  "SOURE"                      "MARITUBA"                   "CURIONOPOLIS"               "ANAPU"                     
[26] "BENEVIDES"                  "ITAITUBA"                   "CAPANEMA"                   "CURUCA"                     "TAILANDIA"                 
[31] "IPIXUNA DO PARA"            "RIO MARIA"                  "OURILANDIA DO NORTE"        "CAPITAO POCO"               "XINGUARA"                  
[36] "PEIXE-BOI"                  "SANTAREM"                   "MAE DO RIO"                 "ULIANOPOLIS"                "GOIANESIA DO PARA"         
[41] "ITUPIRANGA"                 "SAO GERALDO DO ARAGUAIA"    "URUARA"                     "NOVO REPARTIMENTO"          "ALMEIRIM"                  
[46] "ELDORADO DOS CARAJAS"       "SAO MIGUEL DO GUAMA"        "MEDICILANDIA"               "ABAETETUBA"                 "BRAGANCA"                  
[51] "PACAJA"                     "TOME-ACU"                   "SANTANA DO ARAGUAIA"        "CONCEICAO DO ARAGUAIA"      "BELTERRA"                  
[56] "GARRAFAO DO NORTE"          "SANTA BARBARA DO PARA"      "SENADOR JOSE PORFIRIO"      "FLORESTA DO ARAGUAIA"       "TRAIRAO"                   
[61] "NOVO PROGRESSO"             "BREVES"                     "SANTA MARIA DO PARA"        "MARACANA"                   "SANTA ISABEL DO PARA"      
[66] "VITORIA DO XINGU"           "SAO DOMINGOS DO ARAGUAIA"   "COLARES"                    "RUROPOLIS"                  "NOVA ESPERANCA DO PIRIA"   
[71] "SANTA MARIA DAS BARREIRAS"  "SANTO ANTONIO DO TAUA"      "NOVA TIMBOTEUA"             "JURUTI"                     "SALVATERRA"                
[76] "PLACAS"                     "MOJU"                       "MOCAJUBA"                   "ALENQUER"                   "SAO JOAO DE PIRABAS"       
[81] "AUGUSTO CORREA"             "OBIDOS"                     "SAO FRANCISCO DO PARA"      "MAGALHAES BARATA"           "IGARAPE-ACU"               
[86] "OUREM"                      "SANTA LUZIA DO PARA"        "MONTE ALEGRE"               "BAIAO"                      "QUATIPURU"                 
[91] "IGARAPE-MIRI"               "BRASIL NOVO"                "CAMETA"                     "TRACUATEUA"                 "MARAPANIM"                 
[96] "AGUA AZUL DO NORTE"         "ABEL FIGUEIREDO"            "VISEU"                      "TERRA ALTA"                 "BONITO"                    
[101] "JABOATAO DOS GUARARAPES"    "PALESTINA DO PARA"          "AURORA DO PARA"             "PATOS"                      "PORTEL"                    
[106] "PRIMAVERA"                  "CURRALINHO"                 "ACARA"                      "SAO JOAO DO ARAGUAIA"       "BANNACH"                   
[111] "PAU D ARCO"                 "BUJARU"                     "IRITUIA"                    "INHANGAPI"                  "SAPUCAIA"                  
[116] "SAO CAETANO DE ODIVELAS"    "PORTO DE MOZ"               "CACHOEIRA DO PIRIA"         "BOM JESUS DO TOCANTINS"     "PRAINHA"                   
[121] "ITAPEMIRIM"                 "SAO DOMINGOS DO CAPIM"      "MACAPA"                     "OEIRAS DO PARA"             "CONCORDIA DO PARA"         
[126] "PONTA DE PEDRAS"            "TERRA NOVA"                 "SANTAREM NOVO"              "MUANA"                      "ACAILANDIA"                
[131] "NOVA IPIXUNA"               "AMAPA"                      "SAO JOAO DA PONTA"          "MELGACO"                    "LARANJAL DO JARI"          
[136] "CACHOEIRA DO ARARI"         "TERRA SANTA"                "MOJUI DOS CAMPOS"           "SANTA CRUZ DO ARARI"        "CURUA"                     
[141] "IMPERATRIZ"                 "VILA NOVA DO MAMORE"        "SAO LUIS"                   "RIO DE JANEIRO"             "BAGRE"                     
[146] "ARAGUAINA"                  "SAO BERNARDO DO CAMPO"      "SANTANA"                    "FLORIANOPOLIS"              "CUMARU DO NORTE"           
[151] "JURUA"                      "TABULEIRO DO NORTE"         "DAVID CANABARRO"            "CAMPO FLORIDO"              "NOVA IGUACU"               
[156] "MURIAE"                     "CAMPINAS"                   "MANAUS"                     "FARO"                       "BRASILIA"                  
[161] "ANAJAS"                     "UBERLANDIA"                 "BELO HORIZONTE"             "GOIANIA"                    "LIMOEIRO DO AJURU"         
[166] "SAO PAULO"                  "CAMPO MAIOR"                "BOCA DO ACRE"               "SANTA LUZIA DO PARUA"       "PORANGATU"                 
[171] "CALDAS NOVAS"               "CABO FRIO"                  "TOCANTINOPOLIS"             "GOIAS"                      "COROATA"                   
[176] "TEFE"                       "BREJO GRANDE DO ARAGUAIA"   "PROMISSAO"                  "AVEIRO"                     "MINACU"                    
[181] "LAGOA DO OURO"              "FORTALEZA"                  "GURUPA"                     "MANACAPURU"                 "COLMEIA"                   
[186] "OLINDA"                     "SAO BERNARDO"               "SANTA INES"                 "PICOS"                      "PICARRA"                   
[191] "SANTA MARIA"                "ALCANTIL"                   "COARI"                      "SANTA RITA"                 "PLANALTO DA SERRA"         
[196] "ITINGA DO MARANHAO"         "TENORIO"                    "TERESINA"                   "GUARANTA DO NORTE"          "SAO SEBASTIAO DA BOA VISTA"
[201] "AFUA"                       "SANTA IZABEL DO PARA"